/** Controller, app and model sources shaped like the react-app template's, for the generator tests. */

export const appSource = `// The application's names and the ids no controller or model owns. Copied into the client module verbatim.

/** The application's names. */
export const app = {
    name: 'DemoApp',
    title: 'Demo App',
    prefix: 'demo',
    rootElementId: 'react-root',
} as const;
`;

export const modelsSource = `// Generated by netsuite-repository. Do not edit.
import type { EntityCreate } from '@amerilux/netsuite-repository';

export interface Department {
    id: number;
    name: string;
}

export interface Employee {
    id: number;
    name: string;
    department: Department;
    supervisor?: Employee;
}

/** What \`create()\` takes for an Employee. */
export type EmployeeCreate = EntityCreate<Employee>;

export interface EmployeeRole {
    roleId: number;
    employeeId: number;
    roleName: string;
}
`;

export const userControllerSource = `/**
 * @NApiVersion 2.1
 * @NScriptType Restlet
 * @NModuleScope SameAccount
 */

import { defineEndpoints, defineRestlet } from '@amerilux/netsuite-api/server';
import { getActiveUserRoles } from '../services/userService';
import type { RoleSummary } from './userRolesController';

/**
 * The user controller: what it sends and receives, the endpoints that do it, and the script that
 * serves them.
 */

/** The caller as the session knows them. */
export interface ActiveUserSummary {
    id: number;
    name: string;
    email: string;
}

export interface RolesResponse {
    user: ActiveUserSummary;
    /** The role the caller logged in with. */
    activeRoleId: number;
    roles: RoleSummary[];
}

export const userEndpoints = defineEndpoints({
    /** The caller and every role assigned to them. Takes no request; the session says who is calling. */
    roles: (): RolesResponse => getActiveUserRoles(),
});

export type UserEndpoints = typeof userEndpoints;

export const post = defineRestlet({
    name: 'user',
    scriptId: 'customscript_demo_user',
    deployId: 'customdeploy_demo_user',
}, userEndpoints);
`;

export const userRolesControllerSource = `/**
 * @NApiVersion 2.1
 * @NScriptType Suitelet
 * @NModuleScope SameAccount
 */

import type { EmployeeRole } from '../types/models.gen';
import { defineEndpoints, defineSuitelet } from '@amerilux/netsuite-api/server';
import { getRolesByEmployee } from '../services/userRolesService';

/** A role as the wire carries it: picked from the generated entity type so it follows the model. */
export type RoleSummary = Pick<EmployeeRole, 'roleId' | 'roleName'>;

export interface ByEmployeeRequest {
    employeeId: number;
}

export interface ByEmployeeResponse {
    employeeId: number;
    /** Every role assigned to the employee, by name. */
    roles: RoleSummary[];
}

export const userRolesEndpoints = defineEndpoints({
    /**
     * Every role assigned to the employee; the service answers 400 for a bad id.
     */
    byEmployee: (request: ByEmployeeRequest): ByEmployeeResponse => getRolesByEmployee(request),
});

export type UserRolesEndpoints = typeof userRolesEndpoints;

export const onRequest = defineSuitelet({
    name: 'userRoles',
    scriptId: 'customscript_demo_user_roles',
    deployId: 'customdeploy_demo_user_roles',
    browser: false,
}, userRolesEndpoints);
`;

export const expectedAppModule = `// Generated by netsuite-api generate from netsuite.ts. Do not edit: change netsuite.ts and run \`npm run generate\`.
/* eslint-disable */

/** The application's names. */
export const app = {
    name: 'DemoApp',
    title: 'Demo App',
    prefix: 'demo',
    rootElementId: 'react-root',
} as const;
`;

export const expectedUserModule = `// Generated by netsuite-api generate from api/src/controllers/userController.ts. Do not edit: change the controller and run \`npm run generate\`.
/* eslint-disable */

import { createApiClient } from '@amerilux/netsuite-api/client';
import type { RoleSummary } from './userRoles.gen';

/** The caller as the session knows them. */
export interface ActiveUserSummary {
    id: number;
    name: string;
    email: string;
}

export interface RolesResponse {
    user: ActiveUserSummary;
    /** The role the caller logged in with. */
    activeRoleId: number;
    roles: RoleSummary[];
}

/** The endpoint signatures of the user controller, as its handlers declare them. */
export type Endpoints = {
    /** The caller and every role assigned to them. Takes no request; the session says who is calling. */
    roles: () => RolesResponse;
};

/** One typed function per endpoint of the user controller: \`user.api.roles(...)\`. */
export const api = createApiClient<Endpoints>({ kind: 'restlet', scriptId: 'customscript_demo_user', deployId: 'customdeploy_demo_user' });
`;

export const expectedUserRolesModule = `// Generated by netsuite-api generate from api/src/controllers/userRolesController.ts. Do not edit: change the controller and run \`npm run generate\`.
// Called by server code only: its types, and no client.
/* eslint-disable */

// Entity types from api/src/types/models.gen.ts, copied so this module stands on its own.

export interface EmployeeRole {
    roleId: number;
    employeeId: number;
    roleName: string;
}

/** A role as the wire carries it: picked from the generated entity type so it follows the model. */
export type RoleSummary = Pick<EmployeeRole, 'roleId' | 'roleName'>;

export interface ByEmployeeRequest {
    employeeId: number;
}

export interface ByEmployeeResponse {
    employeeId: number;
    /** Every role assigned to the employee, by name. */
    roles: RoleSummary[];
}

/** The endpoint signatures of the userRoles controller, as its handlers declare them. */
export type Endpoints = {
    /**
     * Every role assigned to the employee; the service answers 400 for a bad id.
     */
    byEmployee: (request: ByEmployeeRequest) => ByEmployeeResponse;
};
`;

export const expectedIndexModule = `// Generated by netsuite-api generate from api/src/controllers. Do not edit: change the controllers and run \`npm run generate\`.
/* eslint-disable */

/** The user controller: its request and response types, and \`user.api\`, one typed function per endpoint. */
export * as user from './user.gen';
/** The userRoles controller: its request and response types only; server code calls it, the browser does not. */
export * as userRoles from './userRoles.gen';
`;

export const expectedScriptsModule = `// Generated by netsuite-api generate from api/src/controllers. Do not edit: change the controller and run \`npm run generate\`.
/* eslint-disable */

import type { ScriptRef } from '@amerilux/netsuite-api';

/** Every script the controllers declare, by controller name: what a repository passes to createSuiteletClient. */
export const scripts = {
    user: { kind: 'restlet', scriptId: 'customscript_demo_user', deployId: 'customdeploy_demo_user' },
    userRoles: { kind: 'suitelet', scriptId: 'customscript_demo_user_roles', deployId: 'customdeploy_demo_user_roles', browser: false },
} as const satisfies Record<string, ScriptRef>;
`;
