/** Controller and model sources shaped like the react-app template's, for the generator tests. */

export const modelsSource = `// Generated by netsuite-repository. Do not edit.
import type { EntityCreate } from '@amerilux/netsuite-repository';

export interface Department {
    id: number;
    name: string;
}

export interface Employee {
    id: number;
    name: string;
    department: Department;
    supervisor?: Employee;
}

/** What \`create()\` takes for an Employee. */
export type EmployeeCreate = EntityCreate<Employee>;

export interface EmployeeRole {
    roleId: number;
    employeeId: number;
    roleName: string;
}
`;

export const userRolesServiceSource = `import type { EmployeeRole } from '../types/models.gen';
import { listEmployeeRolesByEmployee } from '../repositories/employeeRolesRepository';

/** A role as the service hands it up: id and name, nothing else. */
export type RoleSummary = Pick<EmployeeRole, 'roleId' | 'roleName'>;

export function toRoleSummary(role: EmployeeRole): RoleSummary {
    return { roleId: role.roleId, roleName: role.roleName };
}

/** Every role assigned to the employee, sorted by name. */
export function getRolesByEmployee(employeeId: number): RoleSummary[] {
    return listEmployeeRolesByEmployee(employeeId).map(toRoleSummary).sort((left, right) => left.roleName.localeCompare(right.roleName));
}
`;

export const userControllerSource = `/**
 * @NApiVersion 2.1
 * @NScriptType Restlet
 * @NModuleScope SameAccount
 */

import { defineEndpoints, defineRestlet } from '@amerilux/netsuite-api/server';
import type { RoleSummary } from '../services/userRolesService';
import { getActiveUserRoles } from '../services/userService';

/**
 * The user controller: what it sends and receives, the endpoints that do it, and the script that
 * serves them.
 */

/** The caller as the session knows them. */
export interface ActiveUserSummary {
    id: number;
    name: string;
    email: string;
}

export interface RolesResponse {
    user: ActiveUserSummary;
    /** The role the caller logged in with. */
    activeRoleId: number;
    roles: RoleSummary[];
}

export const userEndpoints = defineEndpoints({
    /** The caller and every role assigned to them. Takes no request; the session says who is calling. */
    roles: (): RolesResponse => {
        const { user, roles } = getActiveUserRoles();
        return { user: { id: user.id, name: user.name, email: user.email }, activeRoleId: user.roleId, roles };
    },
});

export type UserEndpoints = typeof userEndpoints;

export const post = defineRestlet({
    name: 'user',
    scriptId: 'customscript_demo_user',
    deployId: 'customdeploy_demo_user',
}, userEndpoints);
`;

export const userRolesControllerSource = `/**
 * @NApiVersion 2.1
 * @NScriptType Suitelet
 * @NModuleScope SameAccount
 */

import { ApiError, defineEndpoints, defineSuitelet } from '@amerilux/netsuite-api/server';
import { getRolesByEmployee, type RoleSummary } from '../services/userRolesService';

export interface ByEmployeeRequest {
    employeeId: number;
}

export interface ByEmployeeResponse {
    employeeId: number;
    /** Every role assigned to the employee, by name. */
    roles: RoleSummary[];
}

/** The wire promises a number; a caller that sends something else gets a 400, not a query for NaN. */
function parseEmployeeId(requested: number | string | undefined): number {
    const parsed = typeof requested === 'string' ? Number.parseInt(requested, 10) : requested;
    if (parsed === undefined || Number.isNaN(parsed) || parsed <= 0) {
        throw ApiError.badRequest('employeeId must be a positive whole number.', { employeeId: requested });
    }
    return parsed;
}

export const userRolesEndpoints = defineEndpoints({
    /**
     * Every role assigned to the employee; 400 for a bad id.
     */
    byEmployee: (request: ByEmployeeRequest): ByEmployeeResponse => {
        const employeeId = parseEmployeeId(request.employeeId);
        return { employeeId, roles: getRolesByEmployee(employeeId) };
    },
});

export type UserRolesEndpoints = typeof userRolesEndpoints;

export const onRequest = defineSuitelet({
    name: 'userRoles',
    scriptId: 'customscript_demo_user_roles',
    deployId: 'customdeploy_demo_user_roles',
    browser: false,
}, userRolesEndpoints);
`;

export const expectedUserModule = `// Generated by netsuite-api generate from api/src/controllers/userController.ts. Do not edit: change the controller and run \`npm run generate\`.
/* eslint-disable */

import { createApiClient } from '@amerilux/netsuite-api/client';

// Types from api/src/services/userRolesService.ts, copied so this module stands on its own.

/** A role as the service hands it up: id and name, nothing else. */
export type RoleSummary = Pick<EmployeeRole, 'roleId' | 'roleName'>;

// Types from api/src/types/models.gen.ts, copied so this module stands on its own.

export interface EmployeeRole {
    roleId: number;
    employeeId: number;
    roleName: string;
}

/** The caller as the session knows them. */
export interface ActiveUserSummary {
    id: number;
    name: string;
    email: string;
}

export interface RolesResponse {
    user: ActiveUserSummary;
    /** The role the caller logged in with. */
    activeRoleId: number;
    roles: RoleSummary[];
}

/** The endpoint signatures of the user controller, as its handlers declare them. */
export type Endpoints = {
    /** The caller and every role assigned to them. Takes no request; the session says who is calling. */
    roles: () => RolesResponse;
};

/** One typed function per endpoint of the user controller: \`user.api.roles(...)\`. */
export const api = createApiClient<Endpoints>({ kind: 'restlet', scriptId: 'customscript_demo_user', deployId: 'customdeploy_demo_user' });
`;

export const expectedUserRolesModule = `// Generated by netsuite-api generate from api/src/controllers/userRolesController.ts. Do not edit: change the controller and run \`npm run generate\`.
// Called by server code only: its types, and no client.
/* eslint-disable */

// Types from api/src/services/userRolesService.ts, copied so this module stands on its own.

/** A role as the service hands it up: id and name, nothing else. */
export type RoleSummary = Pick<EmployeeRole, 'roleId' | 'roleName'>;

// Types from api/src/types/models.gen.ts, copied so this module stands on its own.

export interface EmployeeRole {
    roleId: number;
    employeeId: number;
    roleName: string;
}

export interface ByEmployeeRequest {
    employeeId: number;
}

export interface ByEmployeeResponse {
    employeeId: number;
    /** Every role assigned to the employee, by name. */
    roles: RoleSummary[];
}

/** The endpoint signatures of the userRoles controller, as its handlers declare them. */
export type Endpoints = {
    /**
     * Every role assigned to the employee; 400 for a bad id.
     */
    byEmployee: (request: ByEmployeeRequest) => ByEmployeeResponse;
};
`;

export const expectedIndexModule = `// Generated by netsuite-api generate from api/src/controllers. Do not edit: change the controllers and run \`npm run generate\`.
/* eslint-disable */

/** The user controller: its request and response types, and \`user.api\`, one typed function per endpoint. */
export * as user from './user.gen';
/** The userRoles controller: its request and response types only; server code calls it, the browser does not. */
export * as userRoles from './userRoles.gen';
`;

export const expectedScriptsModule = `// Generated by netsuite-api generate from api/src/controllers. Do not edit: change the controller and run \`npm run generate\`.
/* eslint-disable */

import type { ScriptRef } from '@amerilux/netsuite-api';

/** Every script the controllers declare, by controller name: what a repository passes to createSuiteletClient. */
export const scripts = {
    user: { kind: 'restlet', scriptId: 'customscript_demo_user', deployId: 'customdeploy_demo_user' },
    userRoles: { kind: 'suitelet', scriptId: 'customscript_demo_user_roles', deployId: 'customdeploy_demo_user_roles', browser: false },
} as const satisfies Record<string, ScriptRef>;
`;

export const staleOrderServiceSource = `import type { Employee } from '../types/models.gen';

/** A sales order old enough to close, as the service hands it up. */
export interface StaleOrder {
    id: number;
    owner: Pick<Employee, 'id' | 'name'>;
}

export function listStaleOrders(olderThanDays: number): StaleOrder[] {
    return olderThanDays > 0 ? [] : [];
}

export function closeOrder(orderId: number): boolean {
    return orderId > 0;
}
`;


/**
 * A job as a developer writes one: an ordinary Map/Reduce script whose stages are NetSuite's own entry
 * points, a file each, and a run opened and closed around them. The file NetSuite loads carries the
 * header and says which stages there are; the shapes on either end of the run are written where the
 * stage that names them lives. Keyed by file name, the way the folder holds them.
 */
/**
 * A job as a developer writes one: an ordinary Map/Reduce script whose stages are NetSuite's own entry
 * points, a file each, built by the typed builders so the JSON and the run are handled for them. The file
 * NetSuite loads carries the header and says which stages there are; the shapes on either end of the run
 * are written where the stage that names them lives. Keyed by file name, the way the folder holds them.
 */
export const closeStaleOrdersJobFiles: Record<string, string> = {
    'closeStaleOrders.ts': `/**
 * @NApiVersion 2.1
 * @NScriptType MapReduceScript
 * @NModuleScope SameAccount
 */

/** Closes the sales orders nobody has touched for long enough, and tallies them by their owner. */
export { getInputData } from './getInputData';
export { map } from './map';
export { reduce } from './reduce';
export { summarize } from './summarize';
`,
    'getInputData.ts': `import { jobs } from '../../../../netsuite';
import { jobGetInputData } from '../../repositories/jobRunRepository';
import { listStaleOrders, type StaleOrder } from '../../services/staleOrderService';

/** What a run of this job is asked to do. */
export interface CloseStaleRequest {
    olderThanDays: number;
}

export const getInputData = jobGetInputData<CloseStaleRequest, StaleOrder>(jobs.closeStaleOrders, (input) => listStaleOrders(input.olderThanDays));
`,
    'map.ts': `import { jobs } from '../../../../netsuite';
import { jobMap } from '../../repositories/jobRunRepository';
import { closeOrder, type StaleOrder } from '../../services/staleOrderService';

export const map = jobMap<StaleOrder, number>(jobs.closeStaleOrders, (order, job) => {
    if (closeOrder(order.id)) job.write(order.owner.name, order.id);
});
`,
    'reduce.ts': `import { jobs } from '../../../../netsuite';
import { jobReduce } from '../../repositories/jobRunRepository';

export const reduce = jobReduce<number, number>(jobs.closeStaleOrders, (key, values, job) => {
    job.write(key, values.length);
});
`,
    'summarize.ts': `import { jobs } from '../../../../netsuite';
import { jobSummarize } from '../../repositories/jobRunRepository';

/** What the run leaves behind for the page that started it. */
export interface CloseStaleResult {
    closed: number;
    owners: string[];
}

export const summarize = jobSummarize<number, CloseStaleResult>(jobs.closeStaleOrders, (summary) => ({
    closed: summary.output.reduce((total, entry) => total + entry.value, 0),
    owners: summary.output.map((entry) => entry.key),
}));
`,
};
