/** Controller and scripts sources shaped like the react-app template's, for the generator tests. */

export const scriptsSource = `import type { ScriptRef } from '@amerilux/netsuite-api';

export const app = { name: 'DemoApp' } as const;

export const scripts = {
    home: { kind: 'suitelet', scriptId: 'customscript_demo_home', deployId: 'customdeploy_demo_home' },
    user: { kind: 'restlet', scriptId: 'customscript_demo_user', deployId: 'customdeploy_demo_user' },
    /** Runs as Administrator; called by the user restlet through the Suitelet client, not by the browser. */
    userRoles: { kind: 'suitelet', scriptId: 'customscript_demo_user_roles', deployId: 'customdeploy_demo_user_roles', browser: false },
    // @netsuite-project:scripts
} as const satisfies Record<string, ScriptRef>;
`;

export const userControllerSource = `/**
 * @NApiVersion 2.1
 * @NScriptType Restlet
 * @NModuleScope SameAccount
 */

import { defineEndpoints, defineRestlet } from '@amerilux/netsuite-api/server';
import { getActiveUserRoles } from '../services/userService';
import type { RoleSummary } from './userRolesController';

/**
 * The user controller: what it sends and receives, the endpoints that do it, and the script that
 * serves them.
 */

/** The caller as the session knows them. */
export interface ActiveUserSummary {
    id: number;
    name: string;
    email: string;
}

export interface UserRolesResponse {
    user: ActiveUserSummary;
    /** The role the caller logged in with. */
    activeRoleId: number;
    roles: RoleSummary[];
}

export const userEndpoints = defineEndpoints({
    /** The caller and every role assigned to them. Takes no request; the session says who is calling. */
    roles: (): UserRolesResponse => getActiveUserRoles(),
});

export type UserEndpoints = typeof userEndpoints;

export const post = defineRestlet('user', userEndpoints);
`;

export const userRolesControllerSource = `/**
 * @NApiVersion 2.1
 * @NScriptType Suitelet
 * @NModuleScope SameAccount
 */

import type { EmployeeRole } from 'common/types/models.gen';
import { defineEndpoints, defineSuitelet } from '@amerilux/netsuite-api/server';
import { getRolesByEmployee } from '../services/userRolesService';

/** A role as the wire carries it: picked from the generated entity type so it follows the model. */
export type RoleSummary = Pick<EmployeeRole, 'roleId' | 'roleName'>;

export interface UserRolesByEmployeeRequest {
    employeeId: number;
}

export interface UserRolesByEmployeeResponse {
    employeeId: number;
    /** Every role assigned to the employee, by name. */
    roles: RoleSummary[];
}

export const userRolesEndpoints = defineEndpoints({
    /**
     * Every role assigned to the employee; the service answers 400 for a bad id.
     */
    byEmployee: (request: UserRolesByEmployeeRequest): UserRolesByEmployeeResponse => getRolesByEmployee(request),
});

export type UserRolesEndpoints = typeof userRolesEndpoints;

export const onRequest = defineSuitelet('userRoles', userRolesEndpoints);
`;

export const expectedClientModule = `// Generated by netsuite-api generate from api/src/controllers. Do not edit: change the controller and run \`npm run generate\`.
/* eslint-disable */

import { createApiClient } from '@amerilux/netsuite-api/client';
import { scripts } from 'common/netsuite';
import type { EmployeeRole } from 'common/types/models.gen';

// user (api/src/controllers/userController.ts)

/** The caller as the session knows them. */
export interface ActiveUserSummary {
    id: number;
    name: string;
    email: string;
}

export interface UserRolesResponse {
    user: ActiveUserSummary;
    /** The role the caller logged in with. */
    activeRoleId: number;
    roles: RoleSummary[];
}

export type UserEndpoints = {
    /** The caller and every role assigned to them. Takes no request; the session says who is calling. */
    roles: () => UserRolesResponse;
};

/** One typed function per endpoint of the user controller: \`userApi.roles(...)\`. */
export const userApi = createApiClient<UserEndpoints>(scripts.user);

// userRoles (api/src/controllers/userRolesController.ts): called by server code only, so types only

/** A role as the wire carries it: picked from the generated entity type so it follows the model. */
export type RoleSummary = Pick<EmployeeRole, 'roleId' | 'roleName'>;

export interface UserRolesByEmployeeRequest {
    employeeId: number;
}

export interface UserRolesByEmployeeResponse {
    employeeId: number;
    /** Every role assigned to the employee, by name. */
    roles: RoleSummary[];
}

export type UserRolesEndpoints = {
    /**
     * Every role assigned to the employee; the service answers 400 for a bad id.
     */
    byEmployee: (request: UserRolesByEmployeeRequest) => UserRolesByEmployeeResponse;
};
`;
