import type { ControllerContract, DeclaredScript, EndpointSignature } from './controllerReader.js';

/**
 * Writes the generated modules. The client module holds the app declarations, every controller's
 * wire shapes and endpoint type, and a typed client for each controller the browser calls: one file,
 * so a DTO that references another controller's type resolves in place and the client never imports
 * from the api. The scripts module is the server-side map a repository passes to createSuiteletClient.
 */

export interface EmittedController {
    contract: ControllerContract;
    /** Where the file's header points a reader: the controller's path relative to the project. */
    sourceLabel: string;
}

export interface EmitClientModuleOptions {
    clientModule: string;
    /** How the header names the sources: `api/src/controllers`. */
    controllersLabel: string;
}

export interface EmitScriptsModuleOptions {
    wireModule: string;
    controllersLabel: string;
}

export interface EmitAppModuleOptions {
    /** How the header names the app file: `netsuite.ts`. */
    appLabel: string;
}

const INDENT = '    ';
const EDIT_NOTICE = 'Do not edit: change the controller and run `npm run generate`.';

function indentJsDoc(jsDoc: string): string {
    return jsDoc
        .split('\n')
        .map((line, index) => (index === 0 ? `${INDENT}${line.trim()}` : `${INDENT} ${line.trim()}`))
        .join('\n');
}

function emitEndpointMember(endpoint: EndpointSignature): string {
    const parameter = endpoint.requestType === undefined ? '' : `request${endpoint.requestOptional ? '?' : ''}: ${endpoint.requestType}`;
    const member = `${INDENT}${endpoint.name}: (${parameter}) => ${endpoint.responseType};`;
    return endpoint.jsDoc ? `${indentJsDoc(endpoint.jsDoc)}\n${member}` : member;
}

function emitTypeImports(controllers: EmittedController[]): string[] {
    const namesByModule = new Map<string, Set<string>>();
    for (const { contract } of controllers) {
        for (const typeImport of contract.typeImports) {
            const names = namesByModule.get(typeImport.moduleSpecifier) ?? new Set<string>();
            typeImport.names.forEach((name) => names.add(name));
            namesByModule.set(typeImport.moduleSpecifier, names);
        }
    }
    return Array.from(namesByModule.keys())
        .sort()
        .map((moduleSpecifier) => `import type { ${Array.from(namesByModule.get(moduleSpecifier) ?? []).sort().join(', ')} } from '${moduleSpecifier}';`);
}

/** The script reference as a literal, as the client module and the scripts module write it. */
function emitScriptRef(script: DeclaredScript): string {
    const browser = script.browser ? '' : ', browser: false';
    return `{ kind: '${script.kind}', scriptId: '${script.scriptId}', deployId: '${script.deployId}'${browser} }`;
}

function emitController({ contract, sourceLabel }: EmittedController): string {
    const browser = contract.script.browser;
    const sections: string[] = [`// ${contract.name} (${sourceLabel})${browser ? '' : ': called by server code only, so types only'}`];
    for (const declaration of contract.typeDeclarations) sections.push(declaration.text);
    const members = contract.endpoints.map(emitEndpointMember);
    // A type alias, not an interface: only an object type literal satisfies the Endpoints index signature.
    sections.push(`export type ${contract.endpointsTypeName} = {\n${members.join('\n')}\n};`);
    if (browser) {
        sections.push(
            `/** One typed function per endpoint of the ${contract.name} controller: \`${contract.clientName}.${contract.endpoints[0]?.name ?? 'endpoint'}(...)\`. */\n` +
                `export const ${contract.clientName} = createApiClient<${contract.endpointsTypeName}>(${emitScriptRef({ ...contract.script, browser: true })});`,
        );
    }
    return sections.join('\n\n');
}

function sortControllers(controllers: EmittedController[]): EmittedController[] {
    return [...controllers].sort((left, right) => left.contract.name.localeCompare(right.contract.name));
}

export function emitClientModule(controllers: EmittedController[], options: EmitClientModuleOptions): string {
    const ordered = sortControllers(controllers);
    const anyBrowserFacing = ordered.some((controller) => controller.contract.script.browser);
    const header = [`// Generated by netsuite-api generate from ${options.controllersLabel}. ${EDIT_NOTICE}`, '/* eslint-disable */'];
    const imports = [...(anyBrowserFacing ? [`import { createApiClient } from '${options.clientModule}';`] : []), ...emitTypeImports(ordered)];
    const body = ordered.map(emitController);
    return `${[header.join('\n'), imports.join('\n'), ...body].filter((section) => section !== '').join('\n\n')}\n`;
}

/** The app file as the client sees it: its exported declarations, verbatim. */
export function emitAppModule(appDeclarations: string[], options: EmitAppModuleOptions): string {
    const header = [`// Generated by netsuite-api generate from ${options.appLabel}. Do not edit: change ${options.appLabel} and run \`npm run generate\`.`, '/* eslint-disable */'];
    return `${[header.join('\n'), ...appDeclarations].join('\n\n')}\n`;
}

export function emitScriptsModule(controllers: EmittedController[], options: EmitScriptsModuleOptions): string {
    const ordered = sortControllers(controllers);
    const entries = ordered.map(({ contract }) => `${INDENT}${contract.name}: ${emitScriptRef(contract.script)},`);
    return [
        `// Generated by netsuite-api generate from ${options.controllersLabel}. ${EDIT_NOTICE}`,
        '/* eslint-disable */',
        '',
        `import type { ScriptRef } from '${options.wireModule}';`,
        '',
        '/** Every script the controllers declare, by controller name: what a repository passes to createSuiteletClient. */',
        'export const scripts = {',
        ...entries,
        '} as const satisfies Record<string, ScriptRef>;',
        '',
    ].join('\n');
}
