import type { ControllerContract, EndpointSignature } from './controllerReader.js';
import type { ScriptRegistryEntry } from './scriptsReader.js';

/**
 * Writes the client module: every controller's wire shapes and endpoint interface, and a typed
 * client for each controller the browser calls. One file, so a DTO that references another
 * controller's type resolves in place and the client never imports from the api.
 */

export interface EmitClientModuleOptions {
    clientModule: string;
    scriptsModule: string;
    /** How the header names the source: `api/src/controllers`. */
    controllersLabel: string;
}

export interface EmittedController {
    contract: ControllerContract;
    /** Where the file's header points a reader: the controller's path relative to the project. */
    sourceLabel: string;
    browser: boolean;
}

const INDENT = '    ';

function indentJsDoc(jsDoc: string): string {
    return jsDoc
        .split('\n')
        .map((line, index) => (index === 0 ? `${INDENT}${line.trim()}` : `${INDENT} ${line.trim()}`))
        .join('\n');
}

function emitEndpointMember(endpoint: EndpointSignature): string {
    const parameter = endpoint.requestType === undefined ? '' : `request${endpoint.requestOptional ? '?' : ''}: ${endpoint.requestType}`;
    const member = `${INDENT}${endpoint.name}: (${parameter}) => ${endpoint.responseType};`;
    return endpoint.jsDoc ? `${indentJsDoc(endpoint.jsDoc)}\n${member}` : member;
}

function emitTypeImports(controllers: EmittedController[]): string[] {
    const namesByModule = new Map<string, Set<string>>();
    for (const { contract } of controllers) {
        for (const typeImport of contract.typeImports) {
            const names = namesByModule.get(typeImport.moduleSpecifier) ?? new Set<string>();
            typeImport.names.forEach((name) => names.add(name));
            namesByModule.set(typeImport.moduleSpecifier, names);
        }
    }
    return Array.from(namesByModule.keys())
        .sort()
        .map((moduleSpecifier) => `import type { ${Array.from(namesByModule.get(moduleSpecifier) ?? []).sort().join(', ')} } from '${moduleSpecifier}';`);
}

function emitController({ contract, sourceLabel, browser }: EmittedController, options: EmitClientModuleOptions): string {
    const sections: string[] = [`// ${contract.name} (${sourceLabel})${browser ? '' : ': called by server code only, so types only'}`];
    for (const declaration of contract.typeDeclarations) sections.push(declaration.text);
    const members = contract.endpoints.map(emitEndpointMember);
    // A type alias, not an interface: only an object type literal satisfies the Endpoints index signature.
    sections.push(`export type ${contract.endpointsTypeName} = {\n${members.join('\n')}\n};`);
    if (browser) {
        sections.push(
            `/** One typed function per endpoint of the ${contract.name} controller: \`${contract.clientName}.${contract.endpoints[0]?.name ?? 'endpoint'}(...)\`. */\n` +
                `export const ${contract.clientName} = createApiClient<${contract.endpointsTypeName}>(scripts.${contract.name});`,
        );
    }
    void options;
    return sections.join('\n\n');
}

export function emitClientModule(controllers: EmittedController[], options: EmitClientModuleOptions): string {
    const ordered = [...controllers].sort((left, right) => left.contract.name.localeCompare(right.contract.name));
    const anyBrowserFacing = ordered.some((controller) => controller.browser);
    const header = [
        `// Generated by netsuite-api generate from ${options.controllersLabel}. Do not edit: change the controller and run \`npm run generate\`.`,
        '/* eslint-disable */',
    ];
    const imports = [
        ...(anyBrowserFacing ? [`import { createApiClient } from '${options.clientModule}';`, `import { scripts } from '${options.scriptsModule}';`] : []),
        ...emitTypeImports(ordered),
    ];
    const body = ordered.map((controller) => emitController(controller, options));
    return `${[header.join('\n'), imports.join('\n'), ...body].filter((section) => section !== '').join('\n\n')}\n`;
}

export function toEmittedController(contract: ControllerContract, entry: ScriptRegistryEntry | undefined, sourceLabel: string): EmittedController {
    return { contract, sourceLabel, browser: entry?.browser ?? true };
}
